# Generated by Django 4.2 on 2023-04-16 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categ',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
